name: WordPress Daily Cron Trigger

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  ping-wp-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger WordPress Cron
        run: |
          curl -I -L --retry 5 --retry-delay 60 --retry-all-errors \
            --connect-timeout 10 -m 60 \
            -H "Cache-Control: no-cache" \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36" \
            "https://www.chenshaoju.cn/wordpress/wp-cron.php?t=$(date +%s)"
